### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by SuperAdam47** [HimbeersaftLP/GroupJoin#1]
PurePerms and PureChat loaded
plugin working but not send messages

**Comment by SuperAdam47** [comment]
if you load CustomAlerts gives you this bug.

**Comment by SuperAdam47** [comment]
@Flavius12 maybe you fix ?

**Comment by HimbeersaftLP** [comment]
That's because CustomAlerts overrides the join message, I can add a workaround for this, but I really wanted to keep the plugin as simple as possible.
