### ISSUE TITLE
API4

### ISSUE THREAD

**Issue by TheFixDev** [HimbeersaftLP/GroupJoin#3]
Hello can you Update this Plugin to API4 please?

**Comment by HimbeersaftLP** [comment]
Yes, I think I can get to it this week

**Comment by TheFixDev** [comment]
Okay thanks nice

**Comment by HimbeersaftLP** [comment]
Done ^^
Thanks for the reminder

**Comment by TheFixDev** [comment]
^^

**Comment by HimbeersaftLP** [comment]
The release is approved now btw
