### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by ghost** [HimbeersaftLP/GroupJoin#6]
Error when 5 players enter at once, the main error is in the main of your plugin, in addition, update its classes! :)

**Comment by HimbeersaftLP** [comment]
@Henry12960 I can't help if you don't send the error here.

**Comment by HimbeersaftLP** [comment]
Hello @Henry12960?

**Comment by ghost** [comment]
Hi, I can't get the bug report because 5 players don't instantly log in again :(

**Comment by ghost** [comment]
I also have an idea, how about a separate entry ad per world? Ex: Only in the lobby

**Comment by HimbeersaftLP** [comment]
> Hi, I can't get the bug report because 5 players don't instantly log in again :(

Is it not in the server.log file?

**Comment by ghost** [comment]
> > Olá, não consigo obter o relatório do bug porque 5 jogadores não logam instantaneamente novamente :(
> 
> Não está no arquivo server.log?

My server.log is huge, but I'll try to find it, when I find it, I'll post the error here

**Comment by HimbeersaftLP** [comment]
Why close?
